import delimited "C:\Users\Keith Luter\Documents\PUBP 705\Final\API_NY.GDP.PCAP.KD_DS2_en_csv_v2.csv", varnames(5) clear
reshape long v, i(countrycode)
ren v dblGDP
drop indicator*
ren _j intYear
replace intYear = intYear + 1955
ren countrycode scode

replace scode = "ANG" if scode == "AGO"
replace scode = "UAE" if scode == "ARE"
replace scode = "AAB" if scode == "ATG"
replace scode = "AUL" if scode == "AUS"
replace scode = "AUS" if scode == "AUT"
replace scode = "BUI" if scode == "BDI"
replace scode = "BFO" if scode == "BFA"
replace scode = "BHM" if scode == "BHS"
replace scode = "BOS" if scode == "BIH"
replace scode = "BAR" if scode == "BRB"
replace scode = "BRU" if scode == "BRN"
replace scode = "BHU" if scode == "BTN"
replace scode = "BOT" if scode == "BWA"
replace scode = "CEN" if scode == "CAF"
replace scode = "IVO" if scode == "CIV"
replace scode = "CAO" if scode == "CMR"
replace scode = "CON" if scode == "COG"
replace scode = "CAP" if scode == "CPV"
replace scode = "COS" if scode == "CRI"
replace scode = "CZR" if scode == "CZE"
replace scode = "DEN" if scode == "DNK"
replace scode = "ALG" if scode == "DZA"
replace scode = "SPN" if scode == "ESP"
replace scode = "FRN" if scode == "FRA"
replace scode = "UKG" if scode == "GBR"
replace scode = "GRG" if scode == "GEO"
replace scode = "GUI" if scode == "GIN"
replace scode = "GAM" if scode == "GMB"
replace scode = "EQG" if scode == "GNQ"
replace scode = "GRN" if scode == "GRD"
replace scode = "GUA" if scode == "GTM"
replace scode = "HON" if scode == "HND"
replace scode = "CRO" if scode == "HRV"
replace scode = "HAI" if scode == "HTI"
replace scode = "INS" if scode == "IDN"
replace scode = "IRE" if scode == "IRL"
replace scode = "ICE" if scode == "ISL"
replace scode = "KZK" if scode == "KAZ"
replace scode = "KYR" if scode == "KGZ"
replace scode = "CAM" if scode == "KHM"
replace scode = "SKN" if scode == "KNA"
replace scode = "ROK" if scode == "KOR"
replace scode = "KUW" if scode == "KWT"
replace scode = "LEB" if scode == "LBN"
replace scode = "LIB" if scode == "LBY"
replace scode = "SLU" if scode == "LCA"
replace scode = "SRI" if scode == "LKA"
replace scode = "LES" if scode == "LSO"
replace scode = "LIT" if scode == "LTU"
replace scode = "LAT" if scode == "LVA"
replace scode = "MOR" if scode == "MAR"
replace scode = "MNC" if scode == "MCO"
replace scode = "MLD" if scode == "MDA"
replace scode = "MAG" if scode == "MDG"
replace scode = "MAD" if scode == "MDV"
replace scode = "MSI" if scode == "MHL"
replace scode = "MAC" if scode == "MKD"
replace scode = "MYA" if scode == "MMR"
replace scode = "MNG" if scode == "MNE"
replace scode = "MON" if scode == "MNG"
replace scode = "MZM" if scode == "MOZ"
replace scode = "MAA" if scode == "MRT"
replace scode = "MAS" if scode == "MUS"
replace scode = "MAW" if scode == "MWI"
replace scode = "MAL" if scode == "MYS"
replace scode = "NIR" if scode == "NER"
replace scode = "NIG" if scode == "NGA"
replace scode = "NTH" if scode == "NLD"
replace scode = "NEP" if scode == "NPL"
replace scode = "NAU" if scode == "NRU"
replace scode = "NEW" if scode == "NZL"
replace scode = "OMA" if scode == "OMN"
replace scode = "PHI" if scode == "PHL"
replace scode = "PAL" if scode == "PLW"
replace scode = "POR" if scode == "PRT"
replace scode = "PAR" if scode == "PRY"
replace scode = "RUM" if scode == "ROU"
replace scode = "SIN" if scode == "SGP"
replace scode = "SOL" if scode == "SLB"
replace scode = "SIE" if scode == "SLE"
replace scode = "SAL" if scode == "SLV"
replace scode = "SNM" if scode == "SMR"
replace scode = "SER" if scode == "SRB"
replace scode = "SLO" if scode == "SVK"
replace scode = "SLV" if scode == "SVN"
replace scode = "SWD" if scode == "SWE"
replace scode = "SWA" if scode == "SWZ"
replace scode = "SWZ" if scode == "CHE"
replace scode = "SEY" if scode == "SYC"
replace scode = "CHA" if scode == "TCD"
replace scode = "TOG" if scode == "TGO"
replace scode = "THI" if scode == "THA"
replace scode = "TAJ" if scode == "TJK"
replace scode = "ETM" if scode == "TLS"
replace scode = "TRI" if scode == "TTO"
replace scode = "TAZ" if scode == "TZA"
replace scode = "URU" if scode == "URY"
replace scode = "SVG" if scode == "VCT"
replace scode = "VIE" if scode == "VNM"
replace scode = "VAN" if scode == "VUT"
replace scode = "YGS" if scode == "XKX"
replace scode = "SAF" if scode == "ZAF"
replace scode = "ZAM" if scode == "ZMB"
replace scode = "ZIM" if scode == "ZWE"

drop if countryname == "Macao SAR, China"
replace scode = "MNG" if countryname == "Montenegro"

drop if inlist(scode, "ARB", "CEB", "CSS", "DEU", "EAP")
drop if inlist(scode, "EAR", "EAS", "ECA", "ECS", "EMU")
drop if inlist(scode, "EUU", "FCS", "HIC", "HPC", "IBD")
drop if inlist(scode, "IBT", "IDA", "IDB", "IDX", "INX")
drop if inlist(scode, "LAC", "LCN", "LDC", "LIC", "LMC")
drop if inlist(scode, "LMY", "LTE", "MEA", "MIC", "MNA")
drop if inlist(scode, "NAC", "OED", "OSS", "PRE", "PSS")
drop if inlist(scode, "PST", "SAS", "OSS", "SUD", "SSA")
drop if inlist(scode, "SSF", "SST", "TEA", "TEC", "TLA")
drop if inlist(scode, "TMN", "TSA", "TSS", "UMC", "WLD")

sa "gdp.dta", replace
